# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:33
from __future__ import unicode_literals

import apps.taggit_autocomplete.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meal'},
        ),
        migrations.AlterField(
            model_name='meal',
            name='tags',
            field=apps.taggit_autocomplete.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurant.Restaurant'),
        ),
    ]
