# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170218_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['title'], 'verbose_name': 'Meal', 'verbose_name_plural': 'Meal'},
        ),
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
