# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 18:35
from __future__ import unicode_literals

import apps.order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170422_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=apps.order.models.order_time),
        ),
    ]
