# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20170422_1835'),
        ('order', '0006_auto_20170429_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponused',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ManyToManyField(blank=True, null=True, through='order.CouponUsed', to='order.Coupon'),
        ),
    ]
